algoritmo "Crachá de Acesso"

var
//atribuíção de variáveis
nome:caractere
idade:inteiro
curso:caractere
n_maquina:real

inicio

    escreval("Digite seu nome: ")
    leia(nome)
    escreval("Informe sua idade:")
    leia(idade)
    escreval("Qual o seu curso?")
    leia(curso)
    escreval("Qual o número da máquina?")
    leia(n_maquina)
    escreva("O aluno "+nome," de idade "+idade+" do curso "+curso+" ,está utilizando a máquina de número "+n_maquina)

fimalgoritmo