algoritmo "RH do SENAI"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Ricardo Silva]
// Descrição   : Você foi contratado para criar o módulo de entrada de dados do sistema de RH do SENAI. O programa deve coletar informações detalhadas de um novo estagiário para salvar no banco de dados.
// Autora    : Eduarda Carvalho

var

nomeC:caractere
idade:caractere
email:caractere
bolsaA:caractere
experiencia:caractere



inicio

nomeC <- "Lucas Ryan"
idade <- "17"
email <- "ryan2606@gmail.com"
bolsaA <- "1200.50"
experiencia <- "Sim"

escreval("__________________________")
escreval("-------RH do SENAI-------")
escreval("__________________________")
escreval("")
escreval ("DIGITE SEU NOME COMPLETO:")
//leia(nomeC)
escreval ("INFORME SUA IDADE:")
//leia(idade)
escreval ("DIGITE SEU E-MAIL:")
//leia(email)
escreval ("INFORME O VALOR DA BOLSA AUXÍLIO:")
//leia(bolsaA)
escreval ("VOCÊ POSSUI ESPERIÊNCIA PRÉVIA?")
//leia(experiencia)
escreval("")

fimalgoritmo